---
version: 2.1

defaults:
  machine:
    image: circleci/classic:latest
  working_directory: ~/caper


machine_defaults: &machine_defaults
  machine:
    image: ubuntu-2004:202010-01
  working_directory: ~/caper


update_apt: &update_apt
  name: Update apt
  command: |
    sudo apt-get update -y
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata


install_python3: &install_python3
  name: Install python3, pip3, java
  command: |
    sudo apt-get install -y software-properties-common git wget curl python3 python3-pip default-jre


install_singularity: &install_singularity
  name: Install Singularity (container)
  command: |
    sudo apt-get install -y alien
    sudo wget https://kojipkgs.fedoraproject.org//packages/singularity/3.8.5/2.el8/x86_64/singularity-3.8.5-2.el8.x86_64.rpm
    sudo alien -d singularity-3.8.5-2.el8.x86_64.rpm
    sudo apt-get install -y ./singularity_3.8.5-3_amd64.deb
    sudo apt-get install -y squashfs-tools
    singularity --version


install_py3_packages: &install_py3_packages
  name: Install Python packages
  command: |
    sudo python3 -m pip install --upgrade pip
    sudo pip install PyYAML --ignore-installed
    sudo pip3 install pyOpenSSL pytest requests dateparser filelock autouri miniwdl pyhocon numpy pandas scikit-learn matplotlib six
    #sudo pip3 install pyOpenSSL pytest requests dateparser filelock autouri miniwdl pyhocon numpy pandas scikit-learn matplotlib "six>=1.13.0" "PyYAML==3.11"
    sudo pip3 install --upgrade pyasn1-modules


install_gcs_lib: &install_gcs_lib
  name: Install Google Cloud SDK (gcloud and gsutil) and Python API (google-cloud-storage)
  command: |
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl -k https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    sudo apt-get update && sudo apt-get install google-cloud-sdk -y
    sudo pip3 install google-cloud-storage


install_aws_lib: &install_aws_lib
  name: Install AWS Python API (boto3) and CLI (awscli)
  command: |
    sudo pip3 install boto3 awscli


jobs:
  pytest:
    <<: *machine_defaults
    steps:
      - checkout
      - run: *update_apt
      - run: *install_python3
      - run: *install_singularity
      - run: *install_py3_packages
      - run: *install_gcs_lib
      - run: *install_aws_lib
      - run:
          no_output_timeout: 60m
          command: |
            cd tests/

            # service account's key file
            echo ${GCLOUD_SERVICE_ACCOUNT_SECRET_JSON} > tmp_key.json
            export KEY_FILE="${PWD}/tmp_key.json"

            # run pytest
            pytest --ci-prefix ${CIRCLE_WORKFLOW_ID} \
                   --gcs-root ${GCS_ROOT} \
                   --gcp-service-account-key-json ${KEY_FILE} \
                   --gcp-prj ${GOOGLE_PROJECT_ID} \
                   --debug-caper \
                   -vv -s

            # auth for gsutil
            export GOOGLE_APPLICATION_CREDENTIALS=${KEY_FILE}
            export GOOGLE_CLOUD_PROJECT=${GOOGLE_PROJECT_ID}
            export BOTO_CONFIG=/dev/null

            # clean up
            rm -f tmp_key.json
            gsutil -m rm -rf ${GCS_ROOT}/caper_out/${CIRCLE_WORKFLOW_ID} || true


# Define workflow here
workflows:
  version: 2.1
  build_workflow:
    jobs:
      - pytest
